device: "cuda"
model_path: "D:/nosaka/checkpoint/holography_noisy/best_checkpoint.pytorch"
model:
  name: UNet3D
  in_channels: 1
  out_channels: 1
  layer_order: gcr
  f_maps: [64, 128, 256, 512, 1024]
  num_groups: 8
  is_segmentation: false
trainer:
  checkpoint_dir: "D:/nosaka/checkpoint/holography_noisy"
  resume: null
  pre_trained: null
  validate_after_iters: 200
  log_after_iters: 50
  max_num_epochs: 100
  max_num_iterations: 100000
  eval_score_higher_is_better: true
  device: "cuda"
optimizer:
  learning_rate: 0.0002
  weight_decay: 0.00001
loss:
  name: SmoothL1Loss
  ignore_index: null
eval_metric:
  name: PSNR
  ignore_index: null
lr_scheduler:
  name: ReduceLROnPlateau
  mode: max
  factor: 0.1
  patience: 10
loaders:
  dataset: StandardHDF5Dataset
  batch_size: 1
  num_workers: 0
  raw_internal_path: raw
  label_internal_path: label
  weight_internal_path: null
  output_dir: "D:/nosaka/outputs/predict/holography_noisy"
  train:
    file_paths:
      - "D:/nosaka/data/3d-holography_output/Train_misty"
    slice_builder:
      name: SliceBuilder
      patch_shape: [128, 128, 128]
      stride_shape: [16, 16, 16]
    transformer:
      raw:
        - name: RandomFlip
        - name: RandomRotate90
        - name: ToTensor
          expand_dims: true
      label:
        - name: RandomFlip
        - name: RandomRotate90
        - name: ToTensor
          expand_dims: true
  val:
    file_paths:
      - "D:/nosaka/data/3d-holography_output/Val_misty"
    slice_builder:
      name: SliceBuilder
      patch_shape: [128, 128, 128]
      stride_shape: [128, 128, 128]
    transformer:
      raw:
        - name: ToTensor
          expand_dims: true
      label:
        - name: ToTensor
          expand_dims: true
  test:
    file_paths:
      - "D:/nosaka/data/3d-holography_output/Test"
    slice_builder:
      name: SliceBuilder
      patch_shape: [128, 128, 128]
      stride_shape: [128, 128, 128]
    transformer:
      raw:
        - name: ToTensor
          expand_dims: true
      label:
        - name: ToTensor
          expand_dims: true
