loaders:
  batch_size: 1
  num_workers: 4
  shuffle: false
  raw_internal_path: raw
  test:
    file_paths:
    - C:\Users\Owner\mizusaki\3d-holography\app\python\3d-imaging\hdf\TIE_2024-07-24_3_128x128.h5
    slice_builder:
      halo_shape:
      - 16
      - 32
      - 32
      name: SliceBuilder
      patch_shape:
      - 128
      - 128
      - 128
      stride_shape:
      - 128
      - 128
      - 128
    transformer:
      raw:
      - name: Normalize
      - expand_dims: true
        name: ToTensor
model:
  f_maps:
  - 64
  - 128
  - 256
  - 512
  - 1024
  in_channels: 1
  is_segmentation: false
  layer_order: gcr
  name: UNet3D
  num_groups: 8
  out_channels: 1
model_path: C:\Users\Owner\mizusaki\pytorch-3dunet\checkpoint\32x32x128\patch=128_stride=16_fm=64_valpatch=128\best_checkpoint.pytorch
predictor:
  name: StandardPredictor
